version: 2.1

orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    working_directory: ~/MvvmApp
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run App Module Unit Tests
#          command: ./gradlew :app:testDebugUnitTest
#      - store_artifacts:
#          path: presentation_layer/build/reports
#      - store_test_results:
#          path: presentation_layer/build/test-results
# Domain layer
      - run:
          name: Run Domain Module Unit Tests
          command: ./gradlew :domain_layer:test
      - store_artifacts:
          path: domain_layer/build/reports
      - store_test_results:
          path: domain_layer/build/test-results
# Presentation layer
      - run:
          name: Run Presentation Module Unit Tests
          command: ./gradlew :presentation_layer:test
      - store_artifacts:
          path: presentation_layer/build/reports
      - store_test_results:
          path: presentation_layer/build/test-results
# Data layer
      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :data_layer:testDebugUnitTest
      - store_artifacts:
          path: data_layer/build/reports
      - store_test_results:
          path: data_layer/build/test-results
# Lint test
      - run:
          name: Run Lint Test
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
